name: Compile idevicerestore
on: [push]
jobs:
  linux-limd:
    strategy:
      matrix:
        arch:
          - runner: ubuntu-22.04
            name: x86_64
          - runner: ubuntu-22.04-arm
            name: aarch64

    name: linux-limd-${{ matrix.arch.name }}
    runs-on: ${{ matrix.arch.runner }}

    steps:
      - uses: actions/checkout@v3

      - name: Run compile script
        run: ./compile.sh limd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libimobiledevice_linux-${{ matrix.arch.name }}
          path: bin
